# -*- coding: utf-8 -*-
"""Generate-historical-supply-chain-data.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KkLkPVQ2TKCL6-VKPBgCTMV-EHKuM0HT
"""

import numpy as np
import pandas as pd

# Set random seed for reproducibility
np.random.seed(42)

# Number of historical records
num_records = 1000

# Generate historical demand data (Normal distribution)
demand = np.random.poisson(lam=50, size=num_records)

# Generate lead time (Discrete values: 1 to 10 days)
lead_time = np.random.randint(1, 11, size=num_records)

# Generate inventory levels (Normal distribution with some noise)
inventory = np.maximum(0, np.random.normal(loc=100, scale=20, size=num_records).astype(int))

# Generate order quantity based on demand fluctuation
order_quantity = np.maximum(0, demand + np.random.randint(-10, 10, size=num_records))

# Generate supplier reliability (percentage between 80% and 100%)
supplier_reliability = np.random.uniform(0.8, 1.0, num_records)

# Create DataFrame
historical_data = pd.DataFrame({
    "Date": pd.date_range(start="2024-01-01", periods=num_records, freq="D"),
    "Demand": demand,
    "Lead_Time": lead_time,
    "Inventory_Level": inventory,
    "Order_Quantity": order_quantity,
    "Supplier_Reliability": supplier_reliability
})

# Save to CSV
historical_data.to_csv("historical_supply_chain_data.csv", index=False)

# Display first few rows
print(historical_data.head())

